### ISSUE TITLE
Application Navigation Font size

### ISSUE THREAD

**Issue by palindromebart** [rackerlabs/design-system#250]
Change Application Navigation font size from 16 px to 14 px.

Make sure the text and redline specs/image both update to 14px.

**Comment by nimbinatus** [comment]
@palindromebart, is this for an image on a page or one of the website pages? Can you provide a link?

**Comment by palindromebart** [comment]
Navigation page: http://helix.rax.io/layout/navigation.html

The redline images need to be changed as well. 
side nav sketch doc: https://drive.google.com/open?id=0BzUmiaOROlWiZmE4d3d6NWxuWWM
top nav sketch doc: https://drive.google.com/open?id=0BzUmiaOROlWiZkpHaUpHdEhadWs

**Comment by nimbinatus** [comment]
Kk, so this ticket is for the specs, not the font size used on the page. Got it!

**Comment by technabors** [comment]
@nimbinatus This is an image and documentation bug / update but I requested @palindromebart to generate an issue so we could track because I won't be able to get to it for a couple days. =)

Sorry for the confusion on this issue. Perhaps we should file an issue to build an issue template for the repo =). So Meta!

**Comment by nimbinatus** [comment]
Yep! I think we'll just use labels like we do on other repos for now. I'll tag this one as a spec update.

**Comment by technabors** [comment]
This was updated and the issue can be closed.
